# Generated by Django 3.0 on 2019-12-14 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('roll', models.CharField(max_length=64, unique=True)),
                ('marks', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
