# Generated by Django 3.0 on 2019-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('address', models.TextField(null=True)),
                ('department', models.CharField(max_length=64, null=True)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
    ]
